config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  root controller: :articles, action: :index
  resources :articles

  post 'articles/new'
  resources :articles, only: [:new, :create]

  post 'articles/edit'
  resources :articles, only: :edit

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates_presence_of :title, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def new
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    render plain: params[:article].inspect
  end
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= link_to 'Save Article', article_path %>

    <%= form.submit %>
  </p>
 
<% end %>

 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Newest News</h1>
    <p>Free journalism</p>
    <br>

<ul>
    <% @articles.each do |article| %>
        <li>
            <%= link_to article.title, article_path(article) %>
            <%= link_to 'New Article', new_article_path(article) %>
            <%= link_to 'Edit Article', edit_article_path(article) %>

        </li>
        <% end %>
</ul>
<% @articles.each do |article| %>

    

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>

  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p><%= @article.title %></p>
<p><%= @article.content %></p>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>